permalink: /:year:month:day/:title
url: "https://dahyeong-yun.github.io/"
baseurl: /home

# variables
name: "Danny's Blog"
description: personal blog of danny
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true